/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.murilo.apresentacao;

import br.edu.ifnmg.murilo.entidade.GastosExtra;
import br.edu.ifnmg.murilo.excecao.CampoObrigatorioException;
import br.edu.ifnmg.murilo.excecao.SistemaControleProducaoException;
import br.edu.ifnmg.murilo.negocio.GastosExtraBO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author murilo
 */
public class CadastrosExtraForm extends javax.swing.JFrame {

    private GastosExtra gastosExtra;
    private GastosExtra editaGastoExtra = null;

    /**
     * Creates new form CastroExtraForm
     */
    public CadastrosExtraForm() {
        this.gastosExtra = new GastosExtra();
        this.preparaTela();
    }

    private void preparaTela() {
        try {
            this.initComponents();

        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Materias Primas Cadastrados", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    private void recuperaCamposTela() {

        if (!txtOutrosGastos.getText().trim().isEmpty()) {
            this.gastosExtra.setOutrasGastos(Double.parseDouble(txtOutrosGastos.getText()));
        }
        this.gastosExtra.setTarifaAgua(Double.parseDouble(txtTarifaAgua.getText()));
        this.gastosExtra.setTarifaLuz(Double.parseDouble(txtTarifaEletricidade.getText()));
    }
    
    private void verificaCamposObrigatorios(){
        if(txtTarifaAgua.getText().trim().isEmpty() || txtTarifaEletricidade.getText().trim().isEmpty()){
            throw new CampoObrigatorioException();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGastosExtras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTarifaEletricidade = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTarifaAgua = new javax.swing.JFormattedTextField();
        lblOutros = new javax.swing.JLabel();
        txtOutrosGastos = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Gastos Extras");
        setLocationByPlatform(true);
        setResizable(false);

        pnlGastosExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos Extras"));

        jLabel1.setText("Tarifa Eletricidade*:");

        jLabel2.setText("Tarifa Água*");

        lblOutros.setText("Outros Gastos");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/add.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGastosExtrasLayout = new javax.swing.GroupLayout(pnlGastosExtras);
        pnlGastosExtras.setLayout(pnlGastosExtrasLayout);
        pnlGastosExtrasLayout.setHorizontalGroup(
            pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGastosExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTarifaEletricidade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGastosExtrasLayout.createSequentialGroup()
                        .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTarifaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGastosExtrasLayout.createSequentialGroup()
                                .addComponent(lblOutros)
                                .addGap(0, 107, Short.MAX_VALUE))
                            .addComponent(txtOutrosGastos)))
                    .addGroup(pnlGastosExtrasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlGastosExtrasLayout.setVerticalGroup(
            pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGastosExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarifaEletricidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarifaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOutrosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(pnlGastosExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGastosExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGastosExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.salvarGastosExtras();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editarGastosExtras();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void salvarGastosExtras() {

        try {
            this.recuperaCamposTela();

            if (editaGastoExtra != null) {
                this.chamarBOParaEditar();
            } else {

                GastosExtraBO gastosExtraBO = new GastosExtraBO();
                gastosExtraBO.inserir(this.gastosExtra);
            }

            JOptionPane.showMessageDialog(this, "Gastos extras cadastrado com sucesso!", "Cadastro de Tijolo", JOptionPane.INFORMATION_MESSAGE);
            this.limpaCamposTela();

        } catch (SistemaControleProducaoException e) {
            String mensagem = "Erro ao realizar operação:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Gastos Extras", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Gastos extras", JOptionPane.ERROR_MESSAGE);
            this.dispose();

        }
    }
    
    private void chamarBOParaEditar() throws SQLException{
        GastosExtraBO gastosExtraBO = new GastosExtraBO();
                gastosExtra.setId(editaGastoExtra.getId());
                gastosExtraBO.atualizar(gastosExtra);
    }

    private void editarGastosExtras() {
        try {
            this.buscaGastosExtra();
            this.inicializaCamposTela();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Gastos extras", JOptionPane.ERROR_MESSAGE);
            this.dispose();

        }
    }

    private void buscaGastosExtra() throws SQLException {
        GastosExtraBO gastosExtraBO = new GastosExtraBO();
        this.editaGastoExtra = gastosExtraBO.buscar();

    }

    private void inicializaCamposTela() {
        if (!(this.editaGastoExtra.getOutrasGastos() == 0 || this.editaGastoExtra.getOutrasGastos() == 0.0)) {
            txtOutrosGastos.setText(String.valueOf(editaGastoExtra.getOutrasGastos()));
        }
        txtTarifaAgua.setText(String.valueOf(editaGastoExtra.getTarifaAgua()));
        txtTarifaEletricidade.setText(String.valueOf(editaGastoExtra.getTarifaLuz()));
    }

    private void limpaCamposTela() {
        txtOutrosGastos.setText("");
        txtTarifaAgua.setText("");
        txtTarifaEletricidade.setText("");
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblOutros;
    private javax.swing.JPanel pnlGastosExtras;
    private javax.swing.JFormattedTextField txtOutrosGastos;
    private javax.swing.JFormattedTextField txtTarifaAgua;
    private javax.swing.JFormattedTextField txtTarifaEletricidade;
    // End of variables declaration//GEN-END:variables
}
