/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.murilo.apresentacao;

import br.edu.ifnmg.murilo.entidade.Funcionario;
import br.edu.ifnmg.murilo.negocio.FuncionarioBO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author murilo
 */
public class ConsultarFuncionariosForm extends Tela {

    private List<Funcionario> funcionarios;
    private CadastroFuncionarioForm novoFuncionario;
    private CadastroFuncionarioForm editarFuncionario;
    private SimpleDateFormat formatador = 
            new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form ConsultarFuncionariosForm
     */
    public ConsultarFuncionariosForm() {
        this.preparaTela();
    }

    private void preparaTela() {
        try {
            this.initComponents();
            this.carregarTabelaFuncionarios();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Materias Primas Cadastrados", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    public void carregarTabelaFuncionarios() throws SQLException {
        FuncionarioBO funcionarioBO = new FuncionarioBO();
        this.funcionarios = funcionarioBO.buscarTodos();

        ModeloTabelaFuncionario modelo = new ModeloTabelaFuncionario();
        tblResultado.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Lista de Funcionários");

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.exibirTelaCadastroFuncionario();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.editarFuncionario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        this.excluirFuncionario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void exibirTelaCadastroFuncionario() {

        if (this.novoFuncionario == null) {
            this.novoFuncionario = new CadastroFuncionarioForm(this);
        }
        novoFuncionario.setVisible(true);
        novoFuncionario.toFront();

    }
    
    private void editarFuncionario() {
        int linhaSelecionada = tblResultado.getSelectedRow();
        if(linhaSelecionada != -1){
            Funcionario funcionarioSelecionado = funcionarios.get(linhaSelecionada);
            
            if(this.editarFuncionario != null){
                this.editarFuncionario.dispose();
            }
            this.editarFuncionario= 
                    new CadastroFuncionarioForm(this, funcionarioSelecionado);
            this.editarFuncionario.setVisible(true);
            
            
        }else{
            String mensagem = "Nenhum aluno selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Edição de aluno",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void excluirFuncionario() {
        try {
            int linhaSelecionada = tblResultado.getSelectedRow();
            if (linhaSelecionada != -1) {
                Funcionario funcionarioSelecionado = funcionarios.get(linhaSelecionada);

                int resposta;
                String mensagem = "Deseja excluir o Funcionário ("
                        + funcionarioSelecionado.getNome() + ")?";
                String titulo = "Exclusão de Funcionário";
                resposta = JOptionPane.showConfirmDialog(this,
                        mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    FuncionarioBO funcionarioBO = new FuncionarioBO();
                    funcionarioBO.excluir(funcionarioSelecionado.getId());
                    String mensagemSuceso = "Funcionário "
                            + funcionarioSelecionado.getNome()
                            + " excluído com sucesso.";
                    JOptionPane.showMessageDialog(this,
                            mensagemSuceso, titulo,
                            JOptionPane.INFORMATION_MESSAGE);

                    this.carregarTabelaFuncionarios();
                }
            } else {
                String mensagem = "Nenhum fornecedor selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Exclusão de fornecedor",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de fornecedor", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables

    private class ModeloTabelaFuncionario extends AbstractTableModel {

        @Override
        public String getColumnName(int coluna) {
            if (coluna == 0) {
                return "Nome";
            } else if (coluna == 1) {
                return "CPF";
            } else if (coluna == 2) {
                return "Logradouro";
            } else if (coluna == 3) {
                return "Número";
            } else if (coluna == 4) {
                return "Bairro";
            } else if (coluna == 5) {
                return "Cidade";
            } else if (coluna == 6) {
                return "Email";
            } else if (coluna == 7) {
                return "Telefone";
            } else if (coluna == 8) {
                return "Data Admissão";
            } else {
                return "Data Nascimento";
            } 
        }

        @Override
        public int getRowCount() {
            return funcionarios.size();
        }

        @Override
        public int getColumnCount() {
            return 10;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            
            
            Funcionario funcionario = funcionarios.get(rowIndex);
            if (columnIndex == 0) {
                return funcionario.getNome();
            } else if (columnIndex == 1) {
                return funcionario.getCpf();
            } else if (columnIndex == 2) {
                return funcionario.getLogradouro();
            } else if (columnIndex == 3) {
                return funcionario.getNumero();
            } else if (columnIndex == 4) {
                return funcionario.getBairro();
            } else if (columnIndex == 5) {
                return funcionario.getCidade();
            } else if (columnIndex == 6) {
                return funcionario.getEmail();
            } else if (columnIndex == 7) {
                return funcionario.getTelefone();
            } else if (columnIndex == 8) {
                return formatador.format(funcionario.getDataAdmissao());
            } else  {
                return formatador.format(funcionario.getDataNascimento());
            } 
        }

    }

}
