/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.murilo.apresentacao;

import br.edu.ifnmg.murilo.entidade.Fornecedor;
import br.edu.ifnmg.murilo.negocio.FornecedorBO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author murilo
 */
public class ConsultarFornecedoresForm extends Tela {

    private List<Fornecedor> fornecedores;

    private CadastroFornecedorForm novoFornecedorForm;
    private CadastroFornecedorForm editarFornecedorForm;

    /**
     * Creates new form ExibirFornecedoresForm
     */
    public ConsultarFornecedoresForm() {
        this.preparaTela();
    }

    private void preparaTela() {
        try {
            this.initComponents();
            this.carregarTabelaFornecedores();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Fornecedores Cadastrados", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    public void carregarTabelaFornecedores() throws SQLException {
        FornecedorBO fornecedorBO = new FornecedorBO();
        this.fornecedores = fornecedorBO.buscarTodos();

        ModeloTabelaFornecedor modelo = new ModeloTabelaFornecedor();
        tblResultado.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Lista de Fornecedores");
        setPreferredSize(new java.awt.Dimension(800, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedores")));

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setMaximumSize(new java.awt.Dimension(52, 27));
        btnNovo.setMinimumSize(new java.awt.Dimension(52, 27));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/murilo/apresentacao/imagens/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluirAluno();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.exibirTelaCadastroFornecedor();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.editarFornecedor();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void editarFornecedor(){
        int linhaSelecionada = tblResultado.getSelectedRow();
        if(linhaSelecionada != -1){
            Fornecedor fornecedorSelecionado = fornecedores.get(linhaSelecionada);
            
            if(this.editarFornecedorForm != null){
                this.editarFornecedorForm.dispose();
            }
            this.editarFornecedorForm= 
                    new CadastroFornecedorForm(this, fornecedorSelecionado);
            this.editarFornecedorForm.setVisible(true);
            this.chamaTabela();
            
        }else{
            String mensagem = "Nenhum aluno selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Edição de aluno",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void chamaTabela(){
        try {
            this.carregarTabelaFornecedores();
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarFornecedoresForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void exibirTelaCadastroFornecedor() {

        if(this.novoFornecedorForm == null){
            this.novoFornecedorForm = new CadastroFornecedorForm(this);
        }
        novoFornecedorForm.setVisible(true);
        novoFornecedorForm.toFront();
        
    }

    private void excluirAluno() {
        try {
            int linhaSelecionada = tblResultado.getSelectedRow();
            if (linhaSelecionada != -1) {
                Fornecedor fonecedorSelecionado = fornecedores.get(linhaSelecionada);

                int resposta;
                String mensagem = "Deseja excluir o fornecedor "
                        + fonecedorSelecionado.getFornecedor()+ " (CNPJ: "
                        + fonecedorSelecionado.getCnpj()+ ")?";
                String titulo = "Exclusão de Fornecedor";
                resposta = JOptionPane.showConfirmDialog(this,
                        mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    FornecedorBO fornecedorBO = new FornecedorBO();
                    fornecedorBO.excluir(fonecedorSelecionado.getCnpj());
                    
                    String mensagemSuceso = "Aluno "+
                            fonecedorSelecionado.getFornecedor()+
                            " (CNPJ: "
                            + fonecedorSelecionado.getCnpj()+ ")"
                            + "excluído com sucesso.";
                    JOptionPane.showMessageDialog(this, 
                            mensagemSuceso, titulo, 
                            JOptionPane.INFORMATION_MESSAGE);
                    
                    this.carregarTabelaFornecedores();
                }
            } else {
                String mensagem = "Nenhum fornecedor selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Exclusão de fornecedor",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de fornecedor", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables

    private class ModeloTabelaFornecedor extends AbstractTableModel {

        @Override
        public String getColumnName(int coluna) {
            if (coluna == 0) {
                return "Fornecedor";
            } else if (coluna == 1) {
                return "CNPJ";
            } else if (coluna == 2) {
                return "Email";
            } else {
                return "Telefone";
            }
        }

        @Override
        public int getRowCount() {
            return fornecedores.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Fornecedor fornecedor = fornecedores.get(rowIndex);
            if (columnIndex == 0) {
                return fornecedor.getFornecedor();
            } else if (columnIndex == 1) {
                return fornecedor.getCnpj();
            } else if (columnIndex == 2) {
                return fornecedor.getEmail();
            } else {
                return fornecedor.getTelefone();
            }
        }

    }

}
